importing necessary libraries

In [1]:
import numpy as np
import pandas as pd
import nltk  #natual-language-tool-kit
from nltk.corpus import stopwords
import string

Getting the dataset from PC

In [2]:
from google.colab import files
uploaded = files.upload()

Saving spam_ham_dataset.csv to spam_ham_dataset.csv


Reading the CSV file

In [3]:
df = pd.read_csv('spam_ham_dataset.csv')
df.head()

Unnamed: 0  ... label_num
0         605  ...         0
1        2349  ...         0
2        3624  ...         0
3        4685  ...         1
4        2030  ...         0

[5 rows x 4 columns]

Exploratory Data Analysis

In [4]:
#seeing the shape of the data frame
df.shape

(5171, 4)

In [5]:
#seeing the names of the columns
df.columns

Index(['Unnamed: 0', 'label', 'text', 'label_num'], dtype='object')

In [9]:
#dropping the duplicates if there are any
df.drop_duplicates(inplace=True)
df.shape

(5171, 4)

In [10]:
#checking if there are any missing data
df.isnull().sum()

Unnamed: 0    0
label         0
text          0
label_num     0
dtype: int64

In [11]:
#download the stopwords package
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [13]:
def process_text(text):
  
  #removing punctuations
  nopunc = [char for char in text if char not in string.punctuation]
  nopunc = ''.join(nopunc)
  
  #removing stopwords(i.e. a, the, an, in etc)
  clean_words = [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]

  #return a list of clean words
  return clean_words


In [14]:
#showing the list of tokens aka lemmas
df['text'].head().apply(process_text)

0    [Subject, enron, methanol, meter, 988291, foll...
1    [Subject, hpl, nom, january, 9, 2001, see, att...
2    [Subject, neon, retreat, ho, ho, ho, around, w...
3    [Subject, photoshop, windows, office, cheap, m...
4    [Subject, indian, springs, deal, book, teco, p...
Name: text, dtype: object

In [ ]:
#convert a collection of text into a matrix of tokens
from sklearn.feature_extraction.text import CountVectorizer
messages_bow = CountVectorizer(analyzer=process_text).fit_transform(df['text']) 
print(messages_bow)

#---Subject--there--Always--
#0--1--------1------0------
#1--1--------1------1------

Splitting the data into train and test

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(messages_bow, df['label_num'], test_size=0.2) #label_num is our output

In [22]:
messages_bow.shape

(5171, 50381)

In [23]:
#training the model
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB().fit(X_train, y_train)

Evaluating the model

In [29]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(X_train)
print(classification_report(y_train, pred))
print()
print('Confusion martix: \n', confusion_matrix(y_train, pred))
print()
print('Accuracy: ', accuracy_score(y_train, pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      2927
           1       0.98      0.98      0.98      1209

    accuracy                           0.99      4136
   macro avg       0.98      0.98      0.98      4136
weighted avg       0.99      0.99      0.99      4136


Confusion martix: 
 [[2901   26]
 [  28 1181]]

Accuracy:  0.9869439071566731


In [30]:
print(classifier.predict(X_test))
print(y_test.values)

[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]


In [31]:
#evaluating our accuracy with the test dataset
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
pred = classifier.predict(X_test)
print(classification_report(y_test, pred))
print()
print('Confusion martix: \n', confusion_matrix(y_test, pred))
print()
print('Accuracy: ', accuracy_score(y_test, pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.98       745
           1       0.96      0.95      0.95       290

    accuracy                           0.97      1035
   macro avg       0.97      0.97      0.97      1035
weighted avg       0.97      0.97      0.97      1035


Confusion martix: 
 [[734  11]
 [ 15 275]]

Accuracy:  0.9748792270531401
